### ISSUE TITLE
not initializing: only a black pygame

### ISSUE THREAD

**Issue by fredguth** [mdeyo/d-star-lite#3]
Hi, 
I did clone, `pip install pygame` and `python3 main.py`.
A black square opens a window with the pygame icon. It seems to be loading something, but eventually does not show anything.
I wonder if it is a problem with the version of pygame, I am using latest pygame (1.9.5) . Any idea on why this is not loading?

Thanks

**Comment by mdeyo** [comment]
@fredguth Quick response: Check out the forked project from issue #2 with your version of pygame. I hope to have time later this week to look into why my project isn't working with it.

**Comment by fredguth** [comment]
The fork did not work as well (tryied in different machine, ubuntu).

**Comment by mdeyo** [comment]
Is your `pip install pygame` for python3? 

Another way to ask the same question: What do you get when you type `pip --version`?

If it says something like `(python 2.7)` then you need to use `pip3 install pygame` instead.

It looks like I also have pygame version 1.9.5 and it's working. This is what you should get:
```
>> python3 main.py 
pygame 1.9.5
Hello from the pygame community. https://www.pygame.org/contribute.html
```

(Closing the issue was an accident)

**Comment by fredguth** [comment]
Ok, I uninstalled pygame and installed again making sure it was python 3 and pip3 (they were default, anyway). This time it worked, thanks!

**Comment by mdeyo** [comment]
Sounds great! Let me know if you need any more help.
